"""add is_superuser to users

Revision ID: 05b6a123b0ec
Revises: 60d09ad5392f
Create Date: 2026-06-15 07:28:12.164509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05b6a123b0ec'
down_revision: Union[str, Sequence[str], None] = '60d09ad5392f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('title', sa.String(), nullable=False))
    op.add_column('items', sa.Column('current_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.drop_column('items', 'is_active')
    op.drop_column('items', 'target_price')
    op.drop_column('items', 'name')
    op.add_column('price_history', sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.drop_column('price_history', 'created_at')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.add_column('price_history', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_column('price_history', 'recorded_at')
    op.add_column('items', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_column('items', 'current_price')
    op.drop_column('items', 'title')
    # ### end Alembic commands ###
