"""add_cascade_delete

Revision ID: 2fb7b519fafd
Revises: b0e06b56d81c
Create Date: 2026-07-10 14:40:09.752092

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2fb7b519fafd"
down_revision: str | Sequence[str] | None = "b0e06b56d81c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
