"""add target price tracking

Revision ID: 5ad822da6410
Revises: 2fb7b519fafd
Create Date: 2026-08-05 16:00:00.443774

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ad822da6410"
down_revision: str | Sequence[str] | None = "2fb7b519fafd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("price_history_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["price_history_id"], ["price_history.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id", "price_history_id", name="uq_notification_event_item_history"
        ),
    )
    op.create_index(
        op.f("ix_notification_events_item_id"),
        "notification_events",
        ["item_id"],
        unique=False,
    )
    op.add_column(
        "items",
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "items",
        sa.Column(
            "currency", sa.String(length=3), server_default="UAH", nullable=False
        ),
    )
    op.add_column(
        "items",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "error",
                name="item_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "items", sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("items", sa.Column("last_error", sa.Text(), nullable=True))
    op.alter_column(
        "items",
        "current_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=True,
    )
    op.execute(
        sa.text("UPDATE items SET status = 'active' WHERE current_price IS NOT NULL")
    )
    op.create_index(op.f("ix_items_status"), "items", ["status"], unique=False)
    op.add_column(
        "price_history",
        sa.Column(
            "currency", sa.String(length=3), server_default="UAH", nullable=False
        ),
    )
    op.alter_column(
        "price_history",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_history",
        "price",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("price_history", "currency")
    op.drop_index(op.f("ix_items_status"), table_name="items")
    op.alter_column(
        "items",
        "current_price",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("items", "last_error")
    op.drop_column("items", "last_checked_at")
    op.drop_column("items", "status")
    op.drop_column("items", "currency")
    op.drop_column("items", "target_price")
    op.drop_index(
        op.f("ix_notification_events_item_id"), table_name="notification_events"
    )
    op.drop_table("notification_events")
    # ### end Alembic commands ###
