"""add_cascade_delete

Revision ID: b0e06b56d81c
Revises: 396a2fb98b7c
Create Date: 2026-07-10 14:18:37.923329

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0e06b56d81c"
down_revision: str | Sequence[str] | None = "396a2fb98b7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("items_user_id_fkey"), "items", type_="foreignkey")
    op.create_foreign_key(
        None, "items", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("price_history_item_id_fkey"), "price_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "price_history", "items", ["item_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("price_history_item_id_fkey"), "price_history", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("price_history_item_id_fkey"),
        "price_history",
        "items",
        ["item_id"],
        ["id"],
    )
    op.drop_constraint(op.f("items_user_id_fkey"), "items", type_="foreignkey")
    op.create_foreign_key(
        op.f("items_user_id_fkey"),
        "items",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
