"""add telegram support

Revision ID: ea1271258fac
Revises: 5ad822da6410
Create Date: 2026-08-07 09:17:11.844819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea1271258fac"
down_revision: str | Sequence[str] | None = "5ad822da6410"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_accounts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_telegram_accounts_chat_id"),
        "telegram_accounts",
        ["chat_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_telegram_accounts_telegram_user_id"),
        "telegram_accounts",
        ["telegram_user_id"],
        unique=True,
    )
    op.create_table(
        "telegram_link_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telegram_link_tokens_expires_at"),
        "telegram_link_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_link_tokens_token_hash"),
        "telegram_link_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_telegram_link_tokens_user_id"),
        "telegram_link_tokens",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "notification_events",
        sa.Column(
            "delivery_status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "failed",
                "skipped",
                name="notification_delivery_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "notification_events",
        sa.Column(
            "delivery_attempts", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "notification_events",
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "notification_events",
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "notification_events",
        sa.Column("last_delivery_error", sa.Text(), nullable=True),
    )
    op.create_index(
        op.f("ix_notification_events_delivery_status"),
        "notification_events",
        ["delivery_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_events_delivery_status"), table_name="notification_events"
    )
    op.drop_column("notification_events", "last_delivery_error")
    op.drop_column("notification_events", "delivered_at")
    op.drop_column("notification_events", "processing_started_at")
    op.drop_column("notification_events", "delivery_attempts")
    op.drop_column("notification_events", "delivery_status")
    op.drop_index(
        op.f("ix_telegram_link_tokens_user_id"), table_name="telegram_link_tokens"
    )
    op.drop_index(
        op.f("ix_telegram_link_tokens_token_hash"), table_name="telegram_link_tokens"
    )
    op.drop_index(
        op.f("ix_telegram_link_tokens_expires_at"), table_name="telegram_link_tokens"
    )
    op.drop_table("telegram_link_tokens")
    op.drop_index(
        op.f("ix_telegram_accounts_telegram_user_id"), table_name="telegram_accounts"
    )
    op.drop_index(op.f("ix_telegram_accounts_chat_id"), table_name="telegram_accounts")
    op.drop_table("telegram_accounts")
    # ### end Alembic commands ###
