name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start infra
        run: docker compose up -d db redis

      - name: Run Pytest
        run: |
          docker compose run --rm \
            -e DATABASE_URL=postgresql+asyncpg://postgres:12345Feo@db:5432/test_postgres \
            -e PYTHONPATH=/app \
            api python -m pytest app/tests

      - name: Stop containers
        if: always()
        run: docker compose down