name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN_SECRET_KEY: ${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
      REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRES_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRES_MINUTES }}
      REFRESH_TOKEN_EXPIRES_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRES_DAYS }}
      DEBUG: ${{ secrets.DEBUG }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
      TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start infra
        run: docker compose up -d db test_db redis

      - name: Build API image
        run: docker compose build api

      - name: Run Pytest
        run: docker compose run --rm api python -m pytest app/tests -v
        continue-on-error: true
        id: pytest_step

      - name: Debug DB Logs (on failure)
        if: always()
        run: |
          echo "--- LOGS FOR test_db ---"
          docker compose logs test_db
          echo "--- LOGS FOR db ---"
          docker compose logs db

      - name: Check Pytest Result
        if: steps.pytest_step.outcome == 'failure'
        run: exit 1

      - name: Stop containers
        if: always()
        run: docker compose down -v