from aiogram import Router
from aiogram.enums import ChatType
from aiogram.filters import Command, CommandStart
from aiogram.filters.command import CommandObject
from aiogram.types import Message
from sqlalchemy import select

from app.database.db import AsyncSessionLocal
from app.models.item import Item
from app.models.telegram_account import TelegramAccount
from app.services.telegram_link_service import consume_link_token

TELEGRAM_MESSAGE_LIMIT = 4000


router = Router(name="telegram")


@router.message(CommandStart())
async def handle_start(message: Message, command: CommandObject):
    if message.chat.type != ChatType.PRIVATE:
        return

    if message.from_user is None:
        return

    raw_token = command.args

    if not raw_token:
        await message.answer(
            "Open the Telegram linking URL generated by Price Tracker."
        )
        return

    async with AsyncSessionLocal() as db:
        linked = await consume_link_token(
            db=db,
            raw_token=raw_token,
            telegram_user_id=message.from_user.id,
            chat_id=message.chat.id,
            username=message.from_user.username,
        )

    if linked:
        await message.answer("Your Telegram account has been linked successfully.")
    else:
        await message.answer(
            "This linking URL is invalid, expired, or has already been used."
        )


@router.message(Command("help"))
async def handle_help(message: Message) -> None:

    if message.chat.type != ChatType.PRIVATE:
        return

    await message.answer(
        "Available commands:\n"
        "/help — show available commands\n"
        "/list — show your tracked items\n"
        "/status — show Telegram linking status\n"
        "/unlink — unlink your Telegram account"
    )


@router.message(Command("status"))
async def handle_status(message: Message) -> None:

    if message.chat.type != ChatType.PRIVATE:
        return

    if message.from_user is None:
        return

    async with AsyncSessionLocal() as db:
        account = await db.scalar(
            select(TelegramAccount).where(
                TelegramAccount.telegram_user_id == message.from_user.id
            )
        )

    if account is None:
        await message.answer("Your Telegram account is not linked to Price Tracker.")
        return

    if not account.is_active:
        await message.answer(
            "Your Telegram link is inactive. "
            "Generate a new linking URL in Price Tracker."
        )
        return

    await message.answer(
        "Your Telegram account is linked and notifications are active."
    )


@router.message(Command("unlink"))
async def handle_unlink(message: Message) -> None:
    if message.chat.type != ChatType.PRIVATE:
        return

    if message.from_user is None:
        return

    async with AsyncSessionLocal() as db:
        account = await db.scalar(
            select(TelegramAccount)
            .where(TelegramAccount.telegram_user_id == message.from_user.id)
            .with_for_update()
        )

        if account is None or not account.is_active:
            await message.answer("Your Telegram account is not currently linked.")
            return

        account.is_active = False
        await db.commit()

    await message.answer("Your Telegram account has been unlinked successfully.")


def build_list_messages(item_blocks: list[str]) -> list[str]:
    full_text = "Your tracked items:\n\n" + "\n\n".join(item_blocks)

    return [
        full_text[start : start + TELEGRAM_MESSAGE_LIMIT]
        for start in range(0, len(full_text), TELEGRAM_MESSAGE_LIMIT)
    ]


@router.message(Command("list"))
async def handle_list(message: Message) -> None:
    if message.chat.type != ChatType.PRIVATE:
        return

    if message.from_user is None:
        return

    async with AsyncSessionLocal() as db:
        account = await db.scalar(
            select(TelegramAccount).where(
                TelegramAccount.telegram_user_id == message.from_user.id,
                TelegramAccount.is_active.is_(True),
            )
        )

        if account is None:
            await message.answer(
                "Link your Telegram account before viewing tracked items."
            )
            return

        result = await db.scalars(
            select(Item).where(Item.user_id == account.user_id).order_by(Item.id)
        )

        items = list(result.all())

    if not items:
        await message.answer("You do not have any tracked items yet.")
        return

    item_blocks: list[str] = []

    for item in items:
        current_price = (
            f"{item.current_price:.2f} {item.currency}"
            if item.current_price is not None
            else "Not available"
        )
        target_price = (
            f"{item.target_price:.2f} {item.currency}"
            if item.target_price is not None
            else "Not set"
        )

        item_blocks.append(
            f"{item.title}\n"
            f"Current price: {current_price}\n"
            f"Target price: {target_price}\n"
            f"Status: {item.status.value}\n"
            f"URL: {item.url}"
        )

    for text in build_list_messages(item_blocks):
        await message.answer(text)
